version: '3.8'

# Group 9 Master Orchestration Core
# Sub-Team A & B: Define microservices, network bridges, and volumes below.


services:
  mysql:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: attendance_db
      MYSQL_USER: attendance_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_backend
    environment:
      DB_HOST: database
      DB_USER: attendance_user
      DB_PASSWORD: password
      DB_NAME: attendance_db
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_frontend
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_started

volumes:
  db_data:
