name: Remote SSH Execution

on:
  push:
    branches:
      - feature/subteam-c-pipeline

jobs:
  ssh-and-execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 1: Initialize the SSH Agent with your encrypted private key secret
      - name: Setup SSH Passphrase Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 2: Connect and execute commands via SSH tunnel
      - name: Execute Commands on Remote EC2 Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            echo 'Connected to EC2 instance successfully!';